[package]
name = "clidle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.7.3", default-features = false, features = ["std"] }
tui = "0.19"
crossterm = "0.25"
rug = "1.17.0"
